export const SUPABASE_PUBLIC_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJndWNvandudXp1cGtqZGxldXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODA2MjY1MTgsImV4cCI6MTk5NjIwMjUxOH0.EFaYONhTuKkgsPGWcyCYbT1bz5s_KWKd7wKWtL1-SXQ";
export const SUPABASE_URL="https://bgucojwnuzupkjdleuwg.supabase.co";
export const SITE_PROTOCOL="http://";
